name: policy-build-release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
    - '*'

jobs:
  release_policy:
    runs-on: ubuntu-latest
    name: build

    steps:
    - uses: actions/checkout@v2

    - name: Policy Login
      id: policy-login
      uses: opcr-io/policy-login-action@v1
      with:
        username: gimmyxd
        password: ${{ secrets.ASERTO_ENG_PUSH_KEY }}

    - name: Policy Build
      id: policy-build
      uses: opcr-io/policy-build-action@v1
      with:
        src: src
        tag: ${{steps.config.outputs.repo }}:${{ steps.sver.outputs.version }}
        revision: "$GITHUB_SHA"

    - name: Policy Push
      id: policy-push
      uses: opcr-io/policy-push-action@v1
      with:
        tag: ${{ steps.config.outputs.repo }}:${{ steps.sver.outputs.version }}

    - name: Policy Logout
      id: policy-logout
      uses: opcr-io/policy-logout-action@v1
